# Generated by Django 5.0.4 on 2025-03-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_productcategory_remove_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='issued_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
