# Generated by Django 5.0.4 on 2025-03-03 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_boq_projectmaster_delete_client_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='primaryOperation',
            new_name='activity',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='cost',
        ),
        migrations.RemoveField(
            model_name='product',
            name='secondaryOperation',
        ),
        migrations.AlterField(
            model_name='boq',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.product'),
        ),
    ]
