# Generated by Django 5.0.4 on 2025-03-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_rename_primaryoperation_product_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boq',
            name='price_per_item',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='boq',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
