# Generated by Django 4.2.6 on 2024-02-25 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='industry',
        ),
    ]
