# Generated by Django 4.2.6 on 2024-02-25 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_remove_contact_industry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='website',
        ),
    ]
