# Generated by Django 4.2.6 on 2024-02-23 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=50)),
                ('probability', models.CharField(max_length=50)),
                ('closeDate', models.DateField()),
                ('createdOn', models.DateField(auto_now_add=True)),
                ('lastContact', models.DateField()),
                ('assignedTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lead.lead')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.stage')),
            ],
        ),
    ]
