# Generated by Django 5.0.4 on 2025-02-26 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dueDate',
            field=models.DateField(blank=True, default=datetime.date(2025, 2, 26), null=True),
        ),
    ]
