# Generated by Django 5.0.4 on 2025-03-06 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_alter_task_duedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dueDate',
            field=models.DateField(blank=True, default=datetime.date(2025, 3, 6), null=True),
        ),
    ]
